=== Ksiona/Tracker/Tracker-war/web/web/xsl/xsd/TrackerXMLScheme.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TrackerXMLScheme.xsd" xmlns="TrackerXMLScheme.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:tns="http:\\localhost\8080\Tracker-war\xsl\xsd TrackerXMLScheme.xsd" 
           targetNamespace="http:\\localhost\8080\Tracker-war\xsl\xsd" 
           elementFormDefault="qualified">
		  
    <xs:element name="employee">
        <xs:complexType >
            <xs:sequence>
                <xs:element name="empId" type="xs:int" minOccurs="1" maxOccurs="1"/>
                <xs:element name="lastName" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="firstName" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="surName" type="xs:string" minOccurs="0" maxOccurs="1"/>            
                <xs:element name="jobTitle" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="login" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="pass" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="department" minOccurs="1" maxOccurs="1"/>
                <xs:element name="permission" minOccurs="1" maxOccurs="1"/>
                <xs:element name="role">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="roleId" type="xs:int" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="roleName" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="productionUnit">
        <xs:complexType >
            <xs:sequence>
                <xs:element name="unitId" type="xs:int" minOccurs="1" />
                <xs:element name="unitTitle" type="xs:string" minOccurs="1" />
                <xs:element name="unitDesc" type="xs:string" minOccurs="0" />
                <xs:element name="conclusionDate" type="xs:date" minOccurs="1" />
                <xs:element name="expireDate" type="xs:date" minOccurs="1" />
                <xs:element name="employee" minOccurs="1" maxOccurs="1" />
                <xs:element name="permission" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
	
    <xs:complexType name="ProductionInit">
        <xs:sequence>
            <xs:element name="unitId" type="xs:int" minOccurs="1" />
            <xs:element name="unitTitle" type="xs:string" minOccurs="1" />
            <xs:element name="unitDesc" type="xs:string" minOccurs="0" />
            <xs:element name="conclusionDate" type="xs:date" minOccurs="1" />
            <xs:element name="expireDate" type="xs:date" minOccurs="1" />
            <xs:element name="employee" minOccurs="1" maxOccurs="1" />
            <xs:element name="permission" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="permission">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="permId" type="xs:int" minOccurs="0" />
                <xs:element name="permissionGroupByReadPer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="groupId" type="xs:int" minOccurs="0" />
                            <xs:element name="groupName" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="permissionGroupByWritePer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="groupId" type="xs:int" minOccurs="0" />
                            <xs:element name="groupName" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
        
    <xs:element name="activity" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="activityDesc" type="xs:string" minOccurs="0" />
                <xs:element name="activityId" type="xs:int" minOccurs="0" />
                <xs:element name="dateWorks" type="xs:date" minOccurs="0" />
                <xs:element name="timeWorked" type="xs:double" minOccurs="0" />
                <xs:element name="activityType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="typeId" type="xs:int" minOccurs="0" />
                            <xs:element name="typeTitle" type="xs:string" minOccurs="0" />
                            <xs:element name="department" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="permission" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="employee"/>
                <xs:element name="permission"/>
                <xs:element name="productionUnit"/>               
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="activityType">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="typeId" type="xs:int" minOccurs="0" />
                <xs:element name="typeTitle" type="xs:string" minOccurs="0" />
                <xs:element name="department" minOccurs="1" maxOccurs="1"/>
                <xs:element name="permission" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="department">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="deptId" type="xs:int" minOccurs="0" />
                <xs:element name="deptName" type="xs:string" minOccurs="0" />
                <xs:element name="permission" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="Department">
        <xs:sequence>
            <xs:element name="deptId" type="xs:int" minOccurs="0" />
            <xs:element name="deptName" type="xs:string" minOccurs="0" />
            <xs:element name="permission" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Ksiona/Tracker/Tracker-war/web/web/xsl/xsd/Employee.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http:\\localhost\8080\Tracker-war\xsl\xsd"
          xsi:schemaLocation="http:\\localhost\8080\Tracker-war\xsl\xsd TrackerXMLScheme.xsd">
    <empId>1</empId>
    <lastName>last</lastName>
    <firstName>first</firstName>
    <surName>sur</surName>
    <jobTitle>job</jobTitle>
    <login>login</login>
    <pass>pass</pass>
    <department>
        <deptId>1</deptId>
        <deptName>IT</deptName>
        <permission>
            <permId>1</permId>
            <permissionGroupByReadPer>
                <groupId>1</groupId>
                <groupName>Dom_admins</groupName>
            </permissionGroupByReadPer>
            <permissionGroupByWritePer>
                <groupId>1</groupId>
                <groupName>Dom_admins</groupName>
            </permissionGroupByWritePer>
        </permission>
    </department>
    <permission>
        <permId>1</permId>
        <permissionGroupByReadPer>
            <groupId>1</groupId>
            <groupName>Dom_admins</groupName>
        </permissionGroupByReadPer>
        <permissionGroupByWritePer>
            <groupId>1</groupId>
            <groupName>Dom_admins</groupName>
        </permissionGroupByWritePer>
    </permission>
    <role>
        <roleId>1</roleId>
        <roleName>mgr1</roleName>
    </role>
</employee>

=== Ksiona/Tracker/Tracker-war/web/web/xsl/xsd/activity.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<activity  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http:\\localhost\8080\Tracker-war\xsl\xsd"
           xsi:schemaLocation="http:\\localhost\8080\Tracker-war\xsl\xsd TrackerXMLScheme.xsd">
    <activityDesc>descr</activityDesc>
    <activityId>1</activityId>
    <dateWorks>2015-03-19</dateWorks>
    <timeWorked>0</timeWorked>
    <activityType>
        <typeId>1</typeId>
        <typeTitle>typeTitle</typeTitle>
        <department>
            <deptId>1</deptId>
            <deptName>IT</deptName>
            <permission>
                <permId>1</permId>
                <permissionGroupByReadPer>
                    <groupId>1</groupId>
                    <groupName>Dom_admins</groupName>
                </permissionGroupByReadPer>
                <permissionGroupByWritePer>
                    <groupId>1</groupId>
                    <groupName>Dom_admins</groupName>
                </permissionGroupByWritePer>
            </permission>
        </department>
        <permission>
            <permId>1</permId>
            <permissionGroupByReadPer>
                <groupId>1</groupId>
                <groupName>Dom_admins</groupName>
            </permissionGroupByReadPer>
            <permissionGroupByWritePer>
                <groupId>1</groupId>
                <groupName>Dom_admins</groupName>
            </permissionGroupByWritePer>
        </permission>

    </activityType>

    <employee>
        <empId>1</empId>
        <lastName>last</lastName>
        <firstName>first</firstName>
        <jobTitle>job</jobTitle>
        <login>login</login>
        <pass>pass</pass>
        <department>
            <deptId>1</deptId>
            <deptName>IT</deptName>
            <permission>
                <permId>1</permId>
                <permissionGroupByReadPer>
                    <groupId>1</groupId>
                    <groupName>Dom_admins</groupName>
                </permissionGroupByReadPer>
                <permissionGroupByWritePer>
                    <groupId>1</groupId>
                    <groupName>Dom_admins</groupName>
                </permissionGroupByWritePer>
            </permission>
        </department>
        <permission>
            <permId>1</permId>
            <permissionGroupByReadPer>
                <groupId>1</groupId>
                <groupName>Dom_admins</groupName>
            </permissionGroupByReadPer>
            <permissionGroupByWritePer>
                <groupId>1</groupId>
                <groupName>Dom_admins</groupName>
            </permissionGroupByWritePer>
        </permission>
        <role>
            <roleId>1</roleId>
            <roleName>mgr1</roleName>
        </role>
    </employee>
    <permission>
        <permId>1</permId>
        <permissionGroupByReadPer>
            <groupId>1</groupId>
            <groupName>Dom_admins</groupName>
        </permissionGroupByReadPer>
        <permissionGroupByWritePer>
            <groupId>1</groupId>
            <groupName>Dom_admins</groupName>
        </permissionGroupByWritePer>
    </permission>
    <productionUnit>
        <conclusionDate>2015-03-19</conclusionDate>
        <expireDate>2015-03-19</expireDate>
        <unitId>1</unitId>
        <unitTitle>unitTitle</unitTitle>
        <permission>
            <permId>1</permId>
            <permissionGroupByReadPer>
                <groupId>1</groupId>
                <groupName>Dom_admins</groupName>
            </permissionGroupByReadPer>
            <permissionGroupByWritePer>
                <groupId>1</groupId>
                <groupName>Dom_admins</groupName>
            </permissionGroupByWritePer>
        </permission>
        <employee>
            <empId>1</empId>
            <lastName>last</lastName>
            <firstName>first</firstName>
            <surName>sur</surName>         
            <jobTitle>job</jobTitle>
            <login>login</login>
            <pass>pass</pass>
            <department>
                <deptId>1</deptId>
                <deptName>IT</deptName>
                <permission>
                    <permId>1</permId>
                    <permissionGroupByReadPer>
                        <groupId>1</groupId>
                        <groupName>Dom_admins</groupName>
                    </permissionGroupByReadPer>
                    <permissionGroupByWritePer>
                        <groupId>1</groupId>
                        <groupName>Dom_admins</groupName>
                    </permissionGroupByWritePer>
                </permission>
            </department>
            <permission>
                <permId>1</permId>
                <permissionGroupByReadPer>
                    <groupId>1</groupId>
                    <groupName>Dom_admins</groupName>
                </permissionGroupByReadPer>
                <permissionGroupByWritePer>
                    <groupId>1</groupId>
                    <groupName>Dom_admins</groupName>
                </permissionGroupByWritePer>
            </permission>
            <role>
                <roleId>1</roleId>
                <roleName>mgr1</roleName>
            </role>
        </employee>
    </productionUnit>

</activity>
